base_url = "https://galactic-forensics.github.io/blog"
title = "Galactic Forensics"
theme = "apollo"
description = "Thoughts and ideas..."

compile_sass = true
generate_feeds = true
build_search_index = false
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
theme = "toggle"              # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/galactic-forensics/blog/tree/main/content"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/galactic-forensics/", icon = "github" },
]

custom_css = []
stylesheets = [
    "override.css"
]

[extra.analytics]
enabled = false
